-- ── Cass: Story guide moment tracking ────────────────────────────────────────

-- Track which Cass moments a user has completed.
-- Prevents re-running onboarding, tracks story readiness across all four moments.
create table if not exists public.cass_moments (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade,
  project_id uuid references public.projects(id) on delete cascade,
  chapter_id uuid references public.boards(id) on delete set null,
  moment text not null,
  -- 'onboarding' | 'chapter_kickoff' | 'retro' | 'story_share'
  completed_at timestamptz default timezone('utc', now()),
  conversation jsonb,   -- full conversation saved for context
  output jsonb          -- structured output (chapter_data, chapter_story, etc.)
);

create index if not exists cass_moments_project
  on public.cass_moments(project_id, moment);

create index if not exists cass_moments_user
  on public.cass_moments(user_id, moment);

alter table public.cass_moments enable row level security;

create policy "Users can manage their own cass moments"
  on public.cass_moments
  for all
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

-- Add chapter_title to boards table (generated by Cass during retro)
alter table public.boards
  add column if not exists chapter_title text;
